/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 29/07/2023 08:47:31
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            37000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_MSI_VALUE                            2097000
#define MX_PLLCLKFreq_Value                     32000000
#define MX_SYSCLKFreq_VALUE                     32000000
#define MX_HCLKFreq_Value                       32000000
#define MX_FCLKCortexFreq_Value                 32000000
#define MX_AHBFreq_Value                        32000000
#define MX_APB1Freq_Value                       32000000
#define MX_APB2Freq_Value                       32000000
#define MX_ADCFreq_Value                        16000000
#define MX_LCDFreq_Value                        37000
#define MX_RTCFreq_Value                        37000
#define MX_RTCHSEDivFreq_Value                  4000000
#define MX_TimerFreq_Value                      32000000
#define MX_VCOOutputFreq_Value                  96000000
#define MX_WatchDogFreq_Value                   37000
#define MX_MCOPinFreq_Value                     32000000
#define MX_VCOInputFreq_Value                   16000000

/*-------------------------------- ADC        --------------------------------*/

#define MX_ADC                                  1

/* GPIO Configuration */

/* Pin PC1 */
#define MX_ADC_IN11_Pin                         PC1
#define MX_ADC_IN11_GPIOx                       GPIOC
#define MX_ADC_IN11_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_IN11_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC_IN11_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PC0 */
#define MX_ADC_IN10_Pin                         PC0
#define MX_ADC_IN10_GPIOx                       GPIOC
#define MX_ADC_IN10_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC_IN10_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC_IN10_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA1 */
#define MX_ADC_IN1_Pin                          PA1
#define MX_ADC_IN1_GPIOx                        GPIOA
#define MX_ADC_IN1_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN1_GPIO_Pin                     GPIO_PIN_1
#define MX_ADC_IN1_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA0-WKUP1 */
#define MX_ADC_IN0_Pin                          PA0_WKUP1
#define MX_ADC_IN0_GPIOx                        GPIOA
#define MX_ADC_IN0_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN0_GPIO_Pin                     GPIO_PIN_0
#define MX_ADC_IN0_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA7 */
#define MX_ADC_IN7_Pin                          PA7
#define MX_ADC_IN7_GPIOx                        GPIOA
#define MX_ADC_IN7_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN7_GPIO_Pin                     GPIO_PIN_7
#define MX_ADC_IN7_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA6 */
#define MX_ADC_IN6_Pin                          PA6
#define MX_ADC_IN6_GPIOx                        GPIOA
#define MX_ADC_IN6_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN6_GPIO_Pin                     GPIO_PIN_6
#define MX_ADC_IN6_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PA4 */
#define MX_ADC_IN4_Pin                          PA4
#define MX_ADC_IN4_GPIOx                        GPIOA
#define MX_ADC_IN4_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN4_GPIO_Pin                     GPIO_PIN_4
#define MX_ADC_IN4_GPIO_Mode                    GPIO_MODE_ANALOG

/* Pin PB1 */
#define MX_ADC_IN9_Pin                          PB1
#define MX_ADC_IN9_GPIOx                        GPIOB
#define MX_ADC_IN9_GPIO_PuPd                    GPIO_NOPULL
#define MX_ADC_IN9_GPIO_Pin                     GPIO_PIN_1
#define MX_ADC_IN9_GPIO_Mode                    GPIO_MODE_ANALOG

/* NVIC Configuration */

/* NVIC ADC1_IRQn */
#define MX_ADC1_IRQn_interruptPremptionPriority 10
#define MX_ADC1_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_ADC1_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13
#define MX_TMS                                  SYS_JTMS_SWDIO

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14
#define MX_TCK                                  SYS_JTCK_SWCLK

/* Pin PB3 */
#define MX_SYS_JTDO_TRACESWO_Pin                PB3
#define MX_SWO                                  SYS_JTDO_TRACESWO

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM2_IRQn */
#define MX_TIM2_IRQn_interruptPremptionPriority 11
#define MX_TIM2_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM2_IRQn_Subriority                 0

/*-------------------------------- TIM5       --------------------------------*/

#define MX_TIM5                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM5_IRQn */
#define MX_TIM5_IRQn_interruptPremptionPriority 13
#define MX_TIM5_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM5_IRQn_Subriority                 0

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PC11 */
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_RX_Pin                         PC11
#define MX_UART4_RX_GPIOx                       GPIOC
#define MX_UART4_RX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_11
#define MX_UART4_RX_GPIO_AF                     GPIO_AF8_UART4
#define MX_UART4_RX_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_UART4_TX_Pin                         PC10
#define MX_UART4_TX_GPIOx                       GPIOC
#define MX_UART4_TX_GPIO_PuPd                   GPIO_PULLUP
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_10
#define MX_UART4_TX_GPIO_AF                     GPIO_AF8_UART4
#define MX_UART4_TX_GPIO_Mode                   GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC UART4_IRQn */
#define MX_UART4_IRQn_interruptPremptionPriority 14
#define MX_UART4_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART4_IRQn_Subriority                0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2

/* Pin PA3 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 12
#define MX_USART2_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13-WKUP2 */
#define MX_PC13_WKUP2_Pin                       PC13_WKUP2
#define MX_PC13_WKUP2_GPIOx                     GPIOC
#define MX_PC13_WKUP2_GPIO_PuPd                 GPIO_NOPULL
#define MX_B1_Blue_PushButton                   PC13_WKUP2
#define MX_PC13_WKUP2_GPIO_Pin                  GPIO_PIN_13
#define MX_PC13_WKUP2_GPIO_ModeDefaultEXTI      GPIO_MODE_IT_RISING

/* Pin PA5 */
#define MX_PA5_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA5_Pin                              PA5
#define MX_PA5_GPIOx                            GPIOA
#define MX_PA5_PinState                         GPIO_PIN_RESET
#define MX_PA5_GPIO_PuPd                        GPIO_NOPULL
#define MX_LD2_Green_Led                        PA5
#define MX_PA5_GPIO_Pin                         GPIO_PIN_5
#define MX_PA5_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */
