//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by app.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDS_COMPANY                     101
#define IDS_PROGRAM                     102
#define IDS_CON_DISCONNECT              103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_REFRESH_DISALLOWED          105
#define IDS_SYSID_INVALID               106
#define IDS_PANE_PROJECT                107
#define IDS_PANE_OUTPUT                 108
#define IDS_PANE_GRAPH                  109
#define IDS_PANE_IMAGE                  110
#define IDS_WARNING_ID_MISMATCH         111
#define IDS_PING_WARN                   112
#define IDS_WARNING_DOC_CONNECT         113
#define IDS_PANE_PARMS                  114
#define IDS_MESSAGE_DROPPED             115
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_DEVICETYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_CONTEXT                     182
#define IDR_SETTINGS                    183
#define IDR_PROJECT                     185
#define IDR_GRAPH                       186
#define IDR_IMAGE                       187
#define IDR_PARMS                       189
#define IDB_INFO                        230
#define IDS_LOG_TAB                     300
#define IDS_DEBUG_TAB                   301
#define IDS_TRAFFIC_TAB                 302
#define ID_VIEW_CUSTOMIZE               310
#define ID_CUSTOMIZE                    310
#define IDB_OMNIWARE_LOGO               311
#define ID_IND_COM                      317
#define IDS_IND_COM                     317
#define ID_IND_COUNT                    318
#define IDS_IND_COUNT                   318
#define ID_IND_CONNECT                  319
#define IDS_IND_CONNECT                 319
#define IDB_BIGRED                      320
#define IDS_IND_TIMER                   320
#define ID_IND_TIMER                    320
#define IDB_BIGGRN                      321
#define IDB_BIGBLU                      322
#define IDB_APP                         331
#define IDC_EDIT_LOG                    400
#define IDC_EDIT_TRAFFIC                401
#define IDC_EDIT_DEBUG                  402
#define IDB_BIGACT                      429
#define ID_TIMER_ONE_SEC                500
#define ID_TIMER_REFRESH                501
#define ID_TIMER_CONNECT                502
#define ID_TIMER_PORT_SEL               503
#define ID_TIMER_RPC_START              504
#define ID_TIMER_PING                   505
#define ID_TIMER_XFER                   506
#define ID_TIMER_CYCLE_RUN              507
#define ID_TIMER_CP_GET                 508
#define ID_TIMER_FILE                   524
#define ID_TIMER_MSG_TIMEOUT            525
#define ID_TIMER_PING_TIMEOUT           526
#define ID_TIMER_ADC                    526
#define ID_TIMER_PID_UPDATE             527
#define ID_TIMER_EMA_UPDATE             528
#define ID_TIMER_ADC_SYNC               529
#define ID_TIMER_DONE_IND               530
#define ID_TIMER_TCP_CLOSE              531
#define IDI_REFRESH_HOT                 660
#define IDI_REFRESH_COLD                661
#define IDD_ABOUT                       1000
#define IDC_PROGRAM                     1001
#define IDC_VERSION                     1002
#define IDC_COMPANY                     1003
#define IDC_OMNIWARE_LINK               1004
#define IDC_DAQ_PACKETS                 1593
#define ID_PANE_PROJECT                 2000
#define ID_PANE_OUTPUT                  2050
#define ID_PANE_GRAPH                   2100
#define ID_PANE_IMAGE                   2150
#define ID_PANE_VTK_IMAGE               2200
#define IDD_CONNECT                     5000
#define IDD_CONNECT_TIP                 5001
#define IDC_CON_PORT_TYPE               5010
#define IDC_CON_PORT_SPEED              5011
#define IDC_CON_PORT_SEL                5012
#define IDC_CON_IP_ADDR                 5020
#define IDC_CON_MAC_ADDR                5021
#define IDC_CON_IP_PORT                 5022
#define IDC_CON_SYS_ID                  5030
#define IDC_CON_FW_REV                  5031
#define IDC_CON_STAMP                   5032
#define IDC_CON_STARTUP                 5040
#define IDC_CON_SRV_CM                  5050
#define IDC_CON_SRV_CP                  5051
#define IDC_CON_CLI_CM                  5052
#define IDC_CON_CLI_CP                  5053
#define IDC_CON_CLI_DAQ                 5054
#define IDC_CON_SRV_DAQ                 5055
#define IDC_CON_CONNECT                 5060
#define IDC_CON_REFRESH                 5061
#define IDC_CON_MSG_STATIC              5080
#define IDC_CON_TYPE_STATIC             5081
#define IDC_CON_PORT_STATIC             5082
#define IDC_CON_SPEED_STATIC            5083
#define IDC_CON_IP_ADDR_STATIC          5084
#define IDC_CON_DEV_STATIC              5085
#define IDC_CON_SERVERS_STATIC          5086
#define IDC_CON_CLIENTS_STATIC          5087
#define IDC_CON_SYS_ID_STATIC           5088
#define IDC_CON_FW_REV_STATIC           5089
#define IDC_CON_STAMP_STATIC            5090
#define IDC_CON_MAC_STATIC              5093
#define IDC_CON_PORT_IP_STATIC          5096
#define IDD_CP                          5200
#define IDD_CP_TIP                      5201
#define IDC_CP_EDIT                     5205
#define IDC_CP_DATA_TYPE                5210
#define IDC_CP_ADDR                     5220
#define IDC_CP_VALUE                    5221
#define IDC_CP_TRACE                    5222
#define IDC_CP_WR                       5230
#define IDC_CP_CI                       5231
#define IDC_CP_CM                       5232
#define IDC_CP_IRQ                      5234
#define IDC_CP_DVR                      5236
#define IDC_CP_RUN                      5237
#define IDC_CP_ERR                      5238
#define IDC_CP_ID                       5239
#define IDC_CP_ROUTE                    5240
#define IDC_CP_UART                     5241
#define IDC_CP_GET                      5250
#define IDC_CP_SET                      5251
#define IDC_CP_TRACE_GET                5252
#define IDC_CP_TRACE_SET                5253
#define IDC_CP_TRACE_ON                 5254
#define IDC_CP_TRACE_OFF                5255
#define IDC_CP_MEM_STATIC               5260
#define IDC_CP_ADDR_STATIC              5261
#define IDC_CP_TRACE_STATIC             5262
#define IDC_CP_VALUE_STATIC             5263
#define IDC_CP_TYPE_STATIC              5264
#define IDD_CP_MEM                      5400
#define IDD_CP_MEMORY                   5400
#define IDD_CP_MEMORY_TIP               5401
#define IDC_CP_MEM_EDIT                 5405
#define IDC_CP_MEM_TYPE                 5410
#define IDC_CP_MEM_FILE                 5420
#define IDC_CP_MEM_START                5421
#define IDC_CP_MEM_LENGTH               5422
#define IDC_CP_MEM_XFER                 5423
#define IDC_CP_MEM_BIN                  5430
#define IDC_CP_MEM_ALL                  5431
#define IDC_CP_MEM_HEX                  5432
#define IDC_CP_MEM_WR                   5433
#define IDC_CP_MEM_CYCLE                5434
#define IDC_CP_MEM_AWGN                 5435
#define IDC_CP_MEM_VERIFY               5436
#define IDC_CP_MEM_SHOW                 5437
#define IDC_CP_MEM_TO_FILE              5438
#define IDC_CP_MEM_READ                 5440
#define IDC_CP_MEM_WRITE                5441
#define IDC_CP_MEM_GET                  5442
#define IDC_CP_MEM_SET                  5443
#define IDC_CP_MEM_CLEAR                5444
#define IDC_CP_MEM_TEST                 5445
#define IDC_CP_MEM_BLK_STATIC           5450
#define IDC_CP_MEM_START_STATIC         5451
#define IDC_CP_MEM_LENGTH_STATIC        5452
#define IDC_CP_MEM_XFER_STATIC          5453
#define IDC_CP_MEM_TYPE_STATIC          5454
#define IDD_DAQ                         5600
#define IDD_DAQ_TIP                     5601
#define IDC_DAQ_EDIT                    5605
#define IDC_DAQ_FILE                    5610
#define IDC_DAQ_TO_FILE                 5620
#define IDC_DAQ_HEX                     5621
#define IDC_DAQ_SHOW                    5622
#define IDC_DAQ_PLOT                    5623
#define IDC_DAQ_RAMP                    5624
#define IDC_DAQ_FLOAT                   5625
#define IDC_DAQ_RAW                     5626
#define IDC_DAQ_START                   5650
#define IDC_DAQ_BLK_STATIC              5660
#define IDC_DAQ_PACKETS_STATIC          5664
#define IDD_CP_RPC                      8600
#define IDD_CP_RPC_TIP                  8601
#define IDC_CP_RPC_EDIT                 8605
#define IDC_CP_RPC_SRV_PORT             8610
#define IDC_CP_RPC_CLI_IP               8611
#define IDC_CP_RPC_CLI_PORT             8612
#define IDC_CP_RPC_SRV_AUTO             8620
#define IDC_CP_RPC_CLI_AUTO             8621
#define IDC_CP_RPC_SRV_START            8630
#define IDC_CP_RPC_CLI_START            8631
#define IDC_CP_RPC_ACTIVE               8632
#define IDC_CP_RPC_SERVER_STATIC        8650
#define IDC_CP_RPC_CLIENT_STATIC        8651
#define IDC_CP_RPC_SRV_PORT_STATIC      8652
#define IDC_CP_RPC_ACTIVE_STATIC        8653
#define IDC_CP_RPC_CLI_PORT_STATIC      8654
#define IDC_CP_RPC_CLI_IP_STATIC        8655
#define IDD_GPH_SETTINGS                9200
#define IDC_GPH_TYPE                    9205
#define IDC_GPH_AUTO                    9210
#define IDC_GPH_CURSOR                  9211
#define IDC_GPH_POINTS                  9212
#define IDC_GPH_X_MIN                   9220
#define IDC_GPH_X_MAX                   9221
#define IDC_GPH_Y_MIN                   9222
#define IDC_GPH_Y_MAX                   9223
#define IDD_IMG_SETTINGS                9400
#define IDD_PRJ_SETTINGS                9600
#define IDC_PRJ_SET_AUTO                9610
#define IDC_PRJ_SET_RELOAD_LAST         9611
#define IDC_PRJ_SET_SYSID_WARN          9612
#define IDC_PRJ_SET_PING_WARN           9615
#define IDC_PRJ_SET_OVERWRITE_WARN      9616
#define IDC_PRJ_SET_MESSAGE_DROPPED_WARN 9617
#define IDC_PRJ_SET_LOG_CM_TRAFFIC      9618
#define IDC_PRJ_SET_LOG_CM_TRAFFIC2     9619
#define IDC_PRJ_SET_BIT_BANG            9619
#define IDD_SRV                         10800
#define IDD_SRV_TIP                     10801
#define IDD_CLI                         11000
#define IDD_CLI_TIP                     11001
#define ID_PARMS_SET                    14001
#define ID_OUTPUT_CLEAR                 32771
#define ID_OUTPUT_COPY_ALL              32772
#define ID_OUTPUT_SAVE                  32773
#define ID_TRAFFIC_CLEAR                32774
#define ID_LOG_CLEAR                    32775
#define ID_LOG_COPY_ALL                 32776
#define ID_LOG_SAVE                     32777
#define ID_TRAFFIC_COPY_ALL             32779
#define ID_TRAFFIC_SAVE                 32780
#define ID_TRAFFIC_ENABLE               32781
#define ID_DEBUG_ENABLE                 32782
#define ID_DEBUG_CLEAR                  32783
#define ID_DEBUG_COPYALL                32784
#define ID_DEBUG_SAVE                   32785
#define ID_DEBUG_COPY_ALL               32786
#define ID_TRAFFIC_STAMP                32787
#define ID_DEBUG_STAMP                  32788
#define ID_LOG_STAMP                    32790
#define ID_PROJECT                      32791
#define ID_GRAPH                        32792
#define ID_IMAGE                        32793
#define ID_EDITEX_CLEAR                 32798
#define ID_EDITEX_COPYALL               32799
#define ID_EDITEX_SAVE                  32800
#define ID_TRAFFIC_LOCAL                32802
#define ID_COLLAPSE_ALL                 32807
#define ID_TRAFFIC_PIPE                 32809
#define ID_GRAPH_1                      32812
#define ID_GRAPH_2                      32813
#define ID_IMAGE_1                      32814
#define ID_IMAGE_2                      32815
#define ID_PROJECT_1                    32816
#define ID_PROJECT_2                    32817
#define ID_FEC_ENABLE                   32821
#define ID_FEC_STAMP                    32822
#define ID_FEC_CLEAR                    32823
#define ID_FEC_SAVE                     32825
#define ID_FEC_COPY_ALL                 32826

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        437
#define _APS_NEXT_COMMAND_VALUE         32832
#define _APS_NEXT_CONTROL_VALUE         1598
#define _APS_NEXT_SYMED_VALUE           374
#endif
#endif
